#!/usr/bin/env bash

set -e

find . -name stack.yaml | while read path; do
    dir=$(dirname $path)
    echo $dir
    pushd $dir >/dev/null
    stack --nix-pure --nix-packages zlib build
    popd >/dev/null
done
